Models/Data.cs
using Lab2_3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_3.Models
{
    public class Data
    {
        public List<Song> listSong { get; set; }
    }
}

Models/Song.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab2_3.Models
{
    public class Song
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
    }
}

Controllers/MusicController.cs
using Lab2_3.Models;
using Lab2_3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab2_3.Controllers
{
    public class MusicController : Controller
    {
        // GET: Music
        Data a = new Data();
        // List<Song> listSong = new List<Song>();

        private List<Song> Initializesongs()
        {
            return new List<Song>
            {
            new Song { Id = 1, Title = "Em là kẻ đáng thương", Artist = "Phát Huy T4", FilePath = "~/Content/EmLaKeDangThuong-PhatHuyT4-8504796.mp3", FileName = "EmLaKeDangThuong-PhatHuyT4-8504796.mp3"},
                new Song { Id = 2, Title = "Một năm mới bình an", Artist = "Sơn Tùng", FilePath = "~/Content/Mot-Nam-Moi-Binh-An-Son-Tung-M-TP.mp3", FileName = "Mot-Nam-Moi-Binh-An-Son-Tung-M-TP.mp3"},
                new Song { Id = 3, Title = "Rồi ta sẽ ngắm pháo hoa cùng nhau", Artist = "Olew VietNam", FilePath = "~/Content/RoiTaSeNgamPhaoHoaCungNhau-OlewVietNam-8485329.mp3", FileName = "RoiTaSeNgamPhaoHoaCungNhau-OlewVietNam-8485329.mp3"},
                new Song { Id = 4, Title = "Bồng bềnh bồng bềnh", Artist = "Nam Em", FilePath = "~/Content/BongBenhBongBenhTheHeroes2022-NamEm-8738686.mp3", FileName = "BongBenhBongBenhTheHeroes2022-NamEm-8738686.mp3"},
                new Song { Id = 5, Title = "Như anh đã thấy em", Artist = "Tim", FilePath = "~/Content/NhuAnhDaThayEm-PhucXPFreakD-7370334.mp3", FileName = "NhuAnhDaThayEm-PhucXPFreakD-7370334.mp3"},
                new Song { Id = 6, Title = "Waiting for you", Artist = "Mono", FilePath = "~/Content/WaitingForYou-MONOOnionn-7733882.mp3", FileName = "WaitingForYou-MONOOnionn-7733882.mp3"},
                new Song { Id = 7, Title = "Lửng Lơ", Artist = "Massew", FilePath = "~/Content/LungLo-MasewBRayRedTYTien-5934275.mp3", FileName = "LungLo-MasewBRayRedTYTien-5934275.mp3"},
                new Song { Id = 8, Title = "Nàng thơ", Artist = "Hoàng Dũng", FilePath = "~/Content/NangTho-HoangDung-6413381.mp3", FileName = "NangTho-HoangDung-6413381.mp3"},
                new Song { Id = 9, Title = "Ánh sao và bầu trời", Artist = "Tri", FilePath = "~/Content/AnhSaoVaBauTroi-TRI-7085073.mp3", FileName = "AnhSaoVaBauTroi-TRI-7085073.mp3"},
                new Song { Id = 10, Title = "Em đồng ý", Artist = "Đức Phúc", FilePath = "~/Content/EmDongYIDo-DucPhucx911-8679310.mp3", FileName = "EmDongYIDo-DucPhucx911-8679310.mp3"}
            };
        }

        public ActionResult Index()
        {

            return View();
        }

        public ActionResult ListMusic()
        {
            a.listSong = Initializesongs();
            ViewBag.listSong = a.listSong;
            //TempData["listSong"] = a.listSong;
            return View();
        }

        public ViewResult DetailsMusic(string filePath, string song_Title, string artist)
        {
            ViewBag.filePath = filePath;
            ViewBag.song_Title = song_Title;
            ViewBag.artist = artist;
            return View();
        }

        public ActionResult PlayMusic(int id)
        {
            return View();
        }

        public FilePathResult Download(string filePath, string fileName)
        {
            string get_path = Server.MapPath(filePath);
            return File(get_path, "music/mp3", fileName);
        }
    }
}

Views/Music/DetailsMusic.cshtml
@{
    ViewBag.Title = "DetailsMusic";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string filePath = ViewBag.filePath;
    string Title = ViewBag.song_Title;
    string artist = ViewBag.artist;
    string filePathUrl = "";

    if (!string.IsNullOrEmpty(filePath))
    {
        filePathUrl = Url.Content(filePath);
    }
}

<h2>@Title - @artist</h2>

<audio controls style="margin-top: 24px;">
    <source src="@filePathUrl" type="audio/ogg">
    <source src="@filePathUrl" type="audio/mp3">
</audio>

<p style="margin-top: 24px;">@Html.ActionLink("Tải Về", "Download", new { filePath = ViewBag.FilePath, fileName = ViewBag.FileName })</p>

Views/Music/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
}

<h2>Bảng xếp hạng quốc tế</h2>

Views/Music/ListMusic.cshtml
@{
    ViewBag.Title = "Nhạc Việt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bảng xếp hạng tháng 8</h2>

<table class="table table-condensed">
    <tbody>
        @for (int i = 0; i < ViewBag.listSong.Count; i++)
        {
            string filePath = ViewBag.listSong[i].FilePath;
            string fileName = ViewBag.listSong[i].FileName;
            string song_Title = ViewBag.listSong[i].Title;
            string Artist = ViewBag.listSong[i].Artist;
            <tr>
                <td>@Html.ActionLink($"{song_Title} - {Artist}", "DetailsMusic", new { filePath = filePath, song_Title = song_Title, artist = Artist }) </td>
                <td>@Html.ActionLink("Tải về", "Download", new { filePath = filePath, fileName = fileName })</td>
            </tr>

        }
    </tbody>

</table>

Views/Music/PlayMusic.cshtml
@{
    ViewBag.Title = "Play";
}

<h2>Play</h2>

<audio controls>
    <source src="~/Content/blue.ogg" type="audio/ogg">
    <source src="~/Content/blue.mp3" type="audio/mp3">
    Your browser does not support the audio element.
</audio>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trang chủ", "Index", "Music", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nhạc Việt Nam", "ListMusic", "Music")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nhạc hay 2023</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>